# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Tycho build with Maven
on:
   push:
      branches:
      - main
   pull_request:
      branches:
      - main
jobs:
   build:
      runs-on: windows-latest
      steps:
      -  name: Checkout
         uses: actions/checkout@v2
         with:
            lfs: true
      -  name: Checkout LFS objects
         run: git lfs checkout
      -  name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
            distribution: adopt
            java-version: '11'
      -  name: Cache Maven packages
         uses: actions/cache@v2.1.4
         with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      -  name: Build with Maven
         run: mvn clean verify
      -  uses: marvinpinto/action-automatic-releases@latest
         with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: latest
            prerelease: true
            title: Development Build
            files: |
               sites/target/swt-cef-browser-*.zip
      -  name: Publish p2 update site
         shell: bash
         env:
            ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
         run: |-
            git clone --branch update-site https://github.com/RoiSoleil/swt-cef-browser
            cd swt-cef-browser
            cd latest
            git config user.name "RoiSoleil"
            git config user.email "helios.gilles@gmail.com"
            rm -fr *
            cp -r ../../sites/target/repository/* .
            git add .
            git commit -m "New version of the update site"
            git push -f https://RoiSoleil:$ACTIONS_TOKEN@github.com/RoiSoleil/swt-cef-browser update-site